### PR TITLE
LRQA-47122 | master

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://issues.liferay.com/browse/LRQA-47122

Note: I didn't cherry-pick to 7.1.x due to portlet cannot be added to display page on 7.1.x.

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:sf

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
The above failures are not caused by this pull.

**Comment by kmaria** [comment]
Pushed to BChan on master https://github.com/brianchandotcom/liferay-portal/pull/70363

**Pull request closed without merging**
