### PR TITLE
LPS-95789 QA - Update testcases according to introduced popup

### PR DESCRIPTION
**Pull request by davidavarga**
https://issues.liferay.com/browse/LPS-95789
https://issues.liferay.com/browse/LRQA-49229

### CODE REVIEW

**Comment by davidavarga** [comment]
ci:test:change-list

**Comment by davidavarga** [comment]
ci:test:change-tracking

**Comment by kmaria** [comment]
ci:test:change-tracking

**Comment by kmaria** [comment]
Pushed to BChan https://github.com/brianchandotcom/liferay-portal/pull/73680

**Pull request closed without merging**
